server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
#    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 422413526525-qtm3jfj1ktqhduqbpl9v0r6n8hn1edb8.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

cloudinary:
  cloud-name: dnsvkorwf
  api-key: 798215572647649
  api-secret: IXmgUxMHFpD3ReSTuf31SGBLtP8
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=



